from datetime import datetime, timezone
from typing import Optional, Tuple

import discord
from discord.app_commands import commands
from discord.ext.commands import Context
from discord.ui import Button

from cogs.sessions import Session
from components.bot import RecruitBot
from components.rqueue import Nation
from components.users import User
from components.views import RecruitView


def recruit(self, bot: RecruitBot, ctx: Context, session: Session = None):
    user = self.bot.rusers.get(ctx.author.id)

    # this will never happen because we validate that the user exists in the command,
    # but my IDE is complaining without it
    if not user:
        return None

    nations = self.bot.queue.get_nations()

    if not nations:
        return None

    rembed = RecruitEmbed(bot, user, session, nations)
    view = rembed.view
    embed = rembed.embed

    bot.daily.info(f"{user.nation} {len(nations)}")

    view.message = await ctx.reply(embed=embed, view=view)
    return nations


class RecruitEmbed():
    bot: RecruitBot
    user: User
    session: Session
    nations: list[Nation]

    # build the embed and view
    def __init__(self):
        color = int("2d0001", 16)
        self.embed = discord.Embed(title=f"Recruit", color=color)
        self.embed.add_field(name="Nations", value="\n".join(
            [f"https://www.nationstates.net/nation={nation}" for nation in self.nations]))
        self.embed.add_field(name="Template",
                             value=f"```{self.user.template}```", inline=False)
        self.embed.set_footer(
            text=f"Initiated by {self.user.nation} at {datetime.now(timezone.utc)}")

        # link buttons can't be created in a subclassed view, so this is basically
        # an empty view with nothing but an on_timeout method
        self.view = RecruitView()
        self.button_ack = discord.ui.Button(label="Acknowledge", style=discord.ButtonStyle.green,
                                            custom_id=(self.session.custom_id + "ack"))
        self.button_send = discord.ui.Button(label="Send TG", style=discord.ButtonStyle.link,
                                             url=f"https://www.nationstates.net/page=compose_telegram?tgto={','.join(nations)}&message=%25{user.template}%25")
        self.button_can = discord.ui.Button(label="Cancel", style=discord.ButtonStyle.red,
                                            custom_id=(self.session.custom_id + "can"))

        # Do not do this if this was generated by /recruit
        if self.session is not None:
            self.view.add_item(self.button_ack)
            self.button_send.disabled = True
            self.acknowledge_button()
        # Do this either way
        self.view.add_item(self.button_send)
        self.cancel_button()

    # return the embed and view
    def get_response(self) -> Optional[Tuple[discord.Embed, RecruitView]]:
        return self.embed, self.view

    # listen for Ack button
    async def acknowledge_button(self, session: Session):
        await self.bot.wait_for('interaction', check=lambda interaction: interaction.data[
                                                                             "component_type"] == 2 and session.custom_id in interaction.data.keys())

        self.button_ack.disabled = True
        self.button_send.disabled = False

    # listen for Cancel button
    async def cancel_button(self, session: Session):
        await self.bot.wait_for('interaction', check=lambda interaction: interaction.data["component_type"] == 2 and (
                session.custom_id + "can") in interaction.data.keys())

        session.cancel_last()
        self.button_ack.disabled = True
        self.button_send.disabled = True
        self.button_can.disabled = True
